name: Android Qt6 CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '**'
    paths-ignore:
      - ".gitignore"
      - "README.md"
      # ignore CI for other platforms
      - ".github/FUNDING.yml"
      - ".github/actions/**"
      - ".github/workflows/Android-Qt5.yml"
      - ".github/workflows/iOS-Qt5.yml"
      - ".github/workflows/iOS-Qt6.yml"
      - ".github/workflows/Linux-Qt5.yml"
      - ".github/workflows/Linux-Qt6.yml"
      - ".github/workflows/macOS-Qt5.yml"
      - ".github/workflows/macOS-Qt6.yml"
      - ".github/workflows/Windows-Qt5.yml"
      - ".github/workflows/Windows-Qt6.yml"

  pull_request:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "README.md"
      # ignore CI for other platforms
      - ".github/FUNDING.yml"
      - ".github/actions/**"
      - ".github/workflows/Android-Qt5.yml"
      - ".github/workflows/iOS-Qt5.yml"
      - ".github/workflows/iOS-Qt6.yml"
      - ".github/workflows/Linux-Qt5.yml"
      - ".github/workflows/Linux-Qt6.yml"
      - ".github/workflows/macOS-Qt5.yml"
      - ".github/workflows/macOS-Qt6.yml"
      - ".github/workflows/Windows-Qt5.yml"
      - ".github/workflows/Windows-Qt6.yml"

concurrency:
  # cancel jobs on PRs only
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  QT_VERSION: 6.3.2
  QT_LOCATION_VERSION: 6.3.2.1

jobs:
  build-plugin:
    name: "Build qt-geoservices-maplibre-gl for ${{ matrix.config.abi }}"
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        config:
          - abi: x86
            arch: android_x86
          - abi: x86_64
            arch: android_x86_64
          - abi: armeabi-v7a
            arch: android_armv7
          - abi: arm64-v8a
            arch: android_arm64_v8a

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: source
          submodules: recursive
          fetch-depth: 0

      - name: Download Qt (desktop)
        id: qt-desktop
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: ==2.1.*
          version: ${{ env.QT_VERSION }}
          modules: qtpositioning qtshadertools

      - name: Download Qt (Android)
        id: qt-android
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: ==2.1.*
          version: ${{ env.QT_VERSION }}
          target: android
          arch: ${{ matrix.config.arch }}
          modules: qtpositioning qtshadertools

      - name: Download QtLocation
        run: |
          wget https://github.com/ntadej/qtlocation/releases/download/v${QT_LOCATION_VERSION}/QtLocation_v${QT_LOCATION_VERSION}_Linux.tar.bz2
          tar xvf QtLocation_v${QT_LOCATION_VERSION}_Linux.tar.bz2 -C ..
          wget https://github.com/ntadej/qtlocation/releases/download/v${QT_LOCATION_VERSION}/QtLocation_v${QT_LOCATION_VERSION}_Android.tar.bz2
          tar xvf QtLocation_v${QT_LOCATION_VERSION}_Android.tar.bz2 -C ..

      - name: Set up OpenJDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: Android-qt-geoservices-maplibre-gl-${{ matrix.config.abi }}

      - name: Build qt-geoservices-maplibre-gl
        env:
          ANDROID_ABI: ${{ matrix.config.abi }}
        run: |
          mkdir build && cd build
          qt-cmake ../source/ \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DQT_HOST_PATH=$(readlink -f $Qt6_DIR/../gcc_64) \
            -DQT_USE_CCACHE=ON
          ninja
          DESTDIR=../install ninja install

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: qt-geoservices-maplibre-gl_Android_${{ matrix.config.abi }}
          path: install/home/runner/work/qt-geoservices-maplibre-gl

  combine-plugin:
    name: "Combine qt-geoservices-maplibre-gl"
    runs-on: ubuntu-22.04
    needs: build-plugin

    steps:
      - name: Download artifacts for x86
        uses: actions/download-artifact@v3
        with:
          name: qt-geoservices-maplibre-gl_Android_x86
          path: install-x86
      
      - name: Download artifacts for x86_64
        uses: actions/download-artifact@v3
        with:
          name: qt-geoservices-maplibre-gl_Android_x86_64
          path: install-x86_64
      
      - name: Download artifacts for armeabi-v7a
        uses: actions/download-artifact@v3
        with:
          name: qt-geoservices-maplibre-gl_Android_armeabi-v7a
          path: install-armeabi-v7a

      - name: Download artifacts for arm64-v8a
        uses: actions/download-artifact@v3
        with:
          name: qt-geoservices-maplibre-gl_Android_arm64-v8a
          path: install-arm64-v8a

      - name: Combine artifacts
        run: |
          cp -r install-arm64-v8a install
          cp -r install-armeabi-v7a/Qt/${QT_VERSION}/* install/Qt/${QT_VERSION}/
          cp -r install-x86/Qt/${QT_VERSION}/* install/Qt/${QT_VERSION}/
          cp -r install-x86_64/Qt/${QT_VERSION}/* install/Qt/${QT_VERSION}/

      - name: Create artifacts
        run: |
          pushd install
          tar cjvf ../qt-geoservices-maplibre-gl_Android.tar.bz2 Qt
          popd

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: qt-geoservices-maplibre-gl_Android
          path: qt-geoservices-maplibre-gl_Android.tar.bz2

  release:
    name: "Release qt-geoservices-maplibre-gl"
    if: github.ref_type == 'tag'
    runs-on: ubuntu-22.04
    needs: combine-plugin
    permissions:
      contents: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: qt-geoservices-maplibre-gl_Android

    - name: Make tarball
      env:
        TAG_NAME: ${{ github.ref_name }}
      run: |
        wget https://github.com/ntadej/qtlocation/releases/download/v${QT_LOCATION_VERSION}/QtLocation_v${QT_LOCATION_VERSION}_Android.tar.bz2
        tar xvf QtLocation_v${QT_LOCATION_VERSION}_Android.tar.bz2
        tar xvf qt-geoservices-maplibre-gl_Android.tar.bz2
        tar cjvf qt-geoservices-maplibre-gl_${TAG_NAME}_Qt${QT_VERSION}_Android.tar.bz2 Qt

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: qt-geoservices-maplibre-gl_${{ github.ref_name }}_Qt${{ env.QT_VERSION }}_Android.tar.bz2
        allowUpdates: true
        draft: true
