name: gh-pages-docs

on:
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1
        with:
          version: "1.12.0"

      - name: Install doxyqml
        run: pip install doxyqml

      - name: Generate documentation
        working-directory: docs
        run: doxygen

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          branch: gh-pages
          folder: docs/output/html
          target-folder: docs
