// Copyright (C) 2023 MapLibre contributors

// SPDX-License-Identifier: BSD-2-Clause

#ifndef QMAPLIBRE_QUICKPRIVATE_EXPORT_H
#define QMAPLIBRE_QUICKPRIVATE_EXPORT_H

#include <QtCore/QtGlobal>

#if !defined(QT_MAPLIBRE_STATIC)
#if defined(QT_BUILD_MAPLIBRE_QUICKPRIVATE_LIB)
#define Q_MAPLIBRE_QUICKPRIVATE_EXPORT Q_DECL_EXPORT
#else
#define Q_MAPLIBRE_QUICKPRIVATE_EXPORT Q_DECL_IMPORT
#endif
#else
#define Q_MAPLIBRE_QUICKPRIVATE_EXPORT
#endif

#endif // QMAPLIBRE_QUICK_PRIVATE_EXPORT_H
